dist: trusty
sudo: false
language: go
go:
- "1.15.6"

env:
  GO111MODULE=off

install:
- make tools

script:
- make test

branches:
  only:
  - master
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
